### ISSUE TITLE
about code release

### ISSUE THREAD

**Issue by amiltonwong** [twmitchel/MobiusConv#1]
Hi, @twmitchel ,

When will the code be released?

**Comment by twmitchel** [comment]
Hi @amiltonwong,

The code will be released within the next week so please keep an eye out!

**Comment by amiltonwong** [comment]
OK, @twmitchel, thanks a lot

**Comment by twmitchel** [comment]
No problem, @amiltonwong. Closing this with the code release, please feel free to email me or open an another issue if you have additional questions or run into problems.
